---
- hosts: unix                                              ##### '{{ my_host }}'
  remote_user: root
  tasks:
    - name: Install zabbix repo
      yum:
       name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
       state: present
    
 ### Naninstalujeme zabbix agenta
    - name: Install zabbix agent and zabbix-sender
      yum:
       name: zabbix-agent zabbix-sender
       state: present
    - name: Enable zabbix service
      systemd:
       name: zabbix-agent
       enabled: yes
      notify:
#      - start Zabbix-agent
#    - name: copy configuration file
#      copy: src=/root/zabbix_agent/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf seuser=system_u
   
    - name: Opening port 10050
      firewalld: port=10050/tcp permanent=true state=enabled 
    - name: Restart zabbix-agent service
      systemd:
       name: zabbix-agent
       state: restarted  
