#!/bin/bash
# Description: Copy ssh generated kyes into clients without asking for password
# Author: Azeem Yusuf
# Date of creation: march 15th 2022
# Date of modification: march 15th 2022
# comments:Note, password shouldnot be displayed plainly as this...

for ip in `cat /root/servers.txt`; do
     sshpass -p "passwd" ssh-copy-id -i /root/.ssh/id_rsa.pub root@$ip
done
